version: '3.0'
services:

  app:
    build: .
    links:
      - postgres
    ports:
      - "8888:8888"
    depends_on:
      - postgres

  postgres:
    image: 'postgres:13'
    container_name: 'database'
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: cinema