version: '1.0'
services:
  app:
    build: .
    links:
      - postgres
    ports:
      - "8888:8888"
    depends_on:
      - postgres

  postgres:
    image: 'postgres:13'
    container_name: 'database'
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_CLIENT_USER}
      POSTGRES_PASSWORD: ${DB_CLIENT_PWD}
      POSTGRES_DB: ${DB_NAME}

